CREATE TABLE "USUARIO"
(    
   "ID" INT not null primary key

        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),   
   "NOME" VARCHAR(20),     
   "LOGIN" VARCHAR(20),
   "SENHA" VARCHAR(20)
);

CREATE TABLE "CONFIGURACAO"
(    
   "ID" INT not null primary key

        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),   
   "VALOR_HORA" NUMERIC(10,2),     
   "VALOR_DIARIA" NUMERIC(10,2),
   "NUM_HORAS_DIARIA" INTEGER
);

CREATE TABLE "VEICULO"
(    
   "ID" INT not null primary key

        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),   
   "PLACA" VARCHAR(8),
   "TIPO" INTEGER
);

CREATE TABLE "MENSALISTA"
(    
   "ID" INT not null primary key

        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),   
   "NOME" VARCHAR(50)
);

CREATE TABLE "MOVIMENTO"
(    
   "ID" INT not null primary key

        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),   
   "PLACA" VARCHAR(8),     
   "DATAHORA_ENTRADA" TIMESTAMP,
   "DATAHORA_SAIDA" TIMESTAMP
);

ALTER TABLE VEICULO ADD IDMENSALISTA INT;
ALTER TABLE MOVIMENTO ADD IDMENSALISTA INT;
ALTER TABLE MOVIMENTO ADD VALOR_HORA NUMERIC(10,2);
ALTER TABLE MOVIMENTO ADD VALOR_DIARIA NUMERIC(10,2);
ALTER TABLE MOVIMENTO ADD VALOR_PAGO NUMERIC(10,2);

INSERT INTO ESTACIONAMENTO.CONFIGURACAO (VALOR_HORA, VALOR_DIARIA, NUM_HORAS_DIARIA) 
	VALUES (2.00, 10.00, 6);

INSERT INTO ESTACIONAMENTO.MENSALISTA (NOME) 
	VALUES ('VICTOR MATHEUS MENDES');
INSERT INTO ESTACIONAMENTO.MENSALISTA (NOME) 
	VALUES ('JOSIAS MARTINS MACEDA');

INSERT INTO ESTACIONAMENTO.MOVIMENTO (PLACA, DATAHORA_ENTRADA, DATAHORA_SAIDA, VALOR_HORA, VALOR_DIARIA, VALOR_PAGO, IDMENSALISTA) 
	VALUES ('MIR-1656', '2015-11-06 21:55:52.005', '2015-11-06 21:55:52.985', 2.00, 6.00, 0.00, 1);
INSERT INTO ESTACIONAMENTO.MOVIMENTO (PLACA, DATAHORA_ENTRADA, DATAHORA_SAIDA, VALOR_HORA, VALOR_DIARIA, VALOR_PAGO, IDMENSALISTA) 
	VALUES ('MGC-2267', '2015-11-07 08:39:20.558', NULL, 2.00, 6.00, 0.00, 2);


INSERT INTO ESTACIONAMENTO.USUARIO (NOME, LOGIN, SENHA) 
	VALUES ('victor', 'victor', 'victor');
INSERT INTO ESTACIONAMENTO.USUARIO (NOME, LOGIN, SENHA) 
	VALUES ('1', '1', '1');
INSERT INTO ESTACIONAMENTO.VEICULO (PLACA, TIPO, IDMENSALISTA) 
	VALUES ('MIR-1656', 1, 1);
